version: '3.7'

services:
  gcsb.cadastrodeclientes.webapi:
    image: acrvivo.azurecr.io/gcsbcadastrodeclienteswebapi
    environment:
      ALLOWED_HOSTS: {ALLOWED_HOSTS} 
      DBCONN: {DBCONN} 
      POSTGRES_LOG_CONN: {POSTGRES_LOG_CONN}
    networks:
        - gcsb-CadastroDeClientes-network
    deploy:      
      replicas: 1
      placement: 
        constraints:
          - node.labels.web == true
      update_config:
        order: start-first
      labels:
        - "traefik.http.routers.CadastroDeClientes.rule=PathPrefix(`/CadastroDeClientes`)"
        - "traefik.http.routers.CadastroDeClientes.service=CadastroDeClientes" # <-----
        - "traefik.http.routers.CadastroDeClientes.middlewares=CadastroDeClientesMid" # <-----
        - "traefik.http.services.CadastroDeClientes.loadbalancer.server.port=80"
        - "traefik.http.middlewares.CadastroDeClientesMid.stripprefix.prefixes=/CadastroDeClientes"
        - "traefik.docker.lbswarm=true"
        - "traefik.enable=true"
        - "traefik.port=80"


networks:
    gcsb-CadastroDeClientes-network:
        name: public
        external: true